# Generated by Django 2.2.2 on 2020-07-22 17:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0021_delete_issuetrack'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueTrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=500)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('comment', models.TextField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(choices=[('1', 'Waiting for staff response'), ('2', 'Waiting for client response'), ('3', 'Closed')], default='1', max_length=200)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects_issue', to='analytics.Project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('work', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='works_issue', to='analytics.Work')),
            ],
        ),
    ]
