# Generated by Django 2.2.6 on 2020-08-01 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuetrack', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuetrack',
            name='title',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
