# Generated by Django 2.2.6 on 2020-08-01 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuetrack', '0002_issuetrack_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuetrack',
            name='image',
            field=models.ImageField(default='default.jpg', null=True, upload_to='profile_pics', verbose_name='Add an image for further details(* Not necessary)'),
        ),
    ]
