# Generated by Django 2.0 on 2020-07-11 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_auto_20200710_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='link',
            field=models.URLField(blank=True, max_length=1280, null=True),
        ),
    ]
