# Generated by Django 2.0 on 2020-07-11 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0006_project_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='https://cdn1.iconfinder.com/data/icons/website-internet/48/website_-_male_business-512.png', upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='work',
            name='status',
            field=models.CharField(choices=[('Not assigned', 'Not assigned'), ('Pending Start', 'Pending Start'), ('In Progress', 'In Progress'), ('Pending for Review', 'Pending for Review'), ('Client Feedback', 'Client Feedback'), ('Completed', 'Completed')], default='assigned', max_length=10),
        ),
    ]
