# Generated by Django 2.0 on 2020-07-12 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0008_auto_20200712_0113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='status',
            field=models.CharField(choices=[('Not assigned', 'Not assigned'), ('Pending Start', 'Pending Start'), ('In Progress', 'In Progress'), ('Pending for Review', 'Pending for Review'), ('Client Feedback', 'Client Feedback'), ('Completed', 'Completed')], default='Not assigned', max_length=20),
        ),
    ]
