# Generated by Django 2.0 on 2020-07-13 12:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0009_auto_20200712_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='deadline',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
