# Generated by Django 2.2.2 on 2020-07-16 14:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analytics', '0011_auto_20200715_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='work',
            name='status',
            field=models.CharField(choices=[('Pending Start', 'Pending Start'), ('In Progress', 'In Progress'), ('Pending for Review', 'Pending for Review'), ('Client Feedback', 'Client Feedback'), ('Completed', 'Completed')], default='Pending Start', max_length=20),
        ),
        migrations.CreateModel(
            name='IssueTrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=500)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('comment', models.TextField(blank=True, max_length=500, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
