# Generated by Django 2.2.2 on 2020-07-17 08:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0012_auto_20200716_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='deadline',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
