# Generated by Django 2.2.2 on 2020-07-21 13:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0014_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
