# Generated by Django 2.2.2 on 2020-07-21 16:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0016_auto_20200721_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='assigned_user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Satff members (Hold down "Control", or "Command" on a Mac, to select more than one)?'),
        ),
    ]
