# Generated by Django 2.2.2 on 2020-07-22 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0019_auto_20200722_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuetrack',
            name='status',
            field=models.CharField(choices=[('1', 'Waiting for staff response'), ('2', 'Waiting for client response'), ('3', 'Closed')], default='1', max_length=200),
        ),
    ]
