# Generated by Django 2.2.2 on 2020-07-22 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0020_issuetrack_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IssueTrack',
        ),
    ]
