# Generated by Django 2.2.2 on 2020-07-24 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0022_auto_20200723_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
