# Generated by Django 2.2.2 on 2020-07-24 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0023_feed_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='link',
            field=models.URLField(blank=True, max_length=1280, null=True),
        ),
    ]
