# Generated by Django 2.2.6 on 2020-07-29 16:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0024_feed_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='goal',
        ),
        migrations.AddField(
            model_name='profile',
            name='link',
            field=models.URLField(blank=True, max_length=1280, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='work',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Start Date'),
        ),
    ]
