# Generated by Django 2.2.6 on 2020-08-01 01:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0026_auto_20200730_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='deadline',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='deadline',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='status',
            field=models.CharField(choices=[('Pending Start', 'Pending Start'), ('In Progress', 'In Progress'), ('Pending for Review', 'Pending for Review'), ('Client Feedback', 'Client Feedback'), ('Completed', 'Completed')], default='Pending Start', max_length=20),
        ),
    ]
