# Generated by Django 2.2.6 on 2020-08-01 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0028_remove_feed_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='link',
            field=models.URLField(blank=True, max_length=1280, null=True, verbose_name='Your Google Drive Link'),
        ),
    ]
