# Generated by Django 2.2.6 on 2020-08-02 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
        ('analytics', '0030_auto_20200802_0058'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tags',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tags.Tags', verbose_name='Add Tags'),
        ),
        migrations.AddField(
            model_name='work',
            name='tags',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tags.Tags', verbose_name='Add Tags'),
        ),
    ]
