# Generated by Django 2.2.6 on 2020-08-03 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
        ('analytics', '0031_auto_20200802_1728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='tags',
        ),
        migrations.AddField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(to='tags.Tags', verbose_name='Add Tags'),
        ),
        migrations.RemoveField(
            model_name='work',
            name='tags',
        ),
        migrations.AddField(
            model_name='work',
            name='tags',
            field=models.ManyToManyField(to='tags.Tags', verbose_name='Add Tags'),
        ),
    ]
