# Generated by Django 2.2.6 on 2020-08-03 09:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0032_auto_20200803_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='assigned_user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Satff members '),
        ),
    ]
