# Generated by Django 2.2.6 on 2020-08-04 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0034_auto_20200804_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='client',
        ),
    ]
