# Generated by Django 2.2.2 on 2020-07-21 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectall', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timelog',
            name='notes',
        ),
        migrations.DeleteModel(
            name='Note',
        ),
        migrations.DeleteModel(
            name='TimeLog',
        ),
    ]
